language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install sqlalchemy
  - pip install pymysql
  - pip install prettytable
  - pip install flask
  - pip install flask_mysqldb
  - pip install pytest
  - pip install mock
  - pip install doubles
# command to run tests
script:
  - echo "Running functional tests"
  - pytest -rA test_bmi.py test_distance.py test_retirement.py test_splitTip.py
  - echo "Running database tests"
  - pytest -rA test_database.py
  - echo "Running web app tests"
  - pytest -rA test_webApp.py